# REPLbot config file

# Slack/Discord bot token used to authorize the bot. The token format is used by REPLbot to figure out
# which kind of token it is.
#
# For Slack:
#   REPLbot requires a Slack "Classic App (bot)", because of its use of the real time messaging (RTM)
#   API. To create a classic app and acquire a Slack bot token, follow these steps:
#     1. Create a classic app: https://api.slack.com/apps?new_classic_app=1
#     2. In the "App Home" section, add a "Legacy bot user"
#     3. In the "OAuth & Permissions" section, click "Install to Workspace"
#     4. Copy the "Bot User OAuth Token" starting with "xoxb-..."
#
# For Discord:
#   1. Create an app: https://discord.com/developers/applications
#   2. In the "Bot" section, click "Add Bot" and disable "Public Bot"
#   3. In the "OAuth2" section, click "Add Redirect" and type a URL (even https://google.com is fine),
#      select the scopes "bot" and "messages.read", and the permissions "public threads", "private thread",
#      "send messages", "manage messages", "manage threads". Click "Save changes".
#   4. Copy the OAuth2 URL and navigate to it in the browser and authorize the app.
#   5. In the "Bot" section, copy the token and paste it here
#
# Format:    long cryptic string
# Default:   None
# Required:  Yes
#
bot-token: MUST_BE_SET

# Directory containing your REPL scripts. REPLbot ships with a bunch of default scripts. Be sure
# to check them out and add/remove scripts as you like.
#
# Security note:
#   Scripts are run in and controlled by a tmux(1) and can be executed from Slack/Discord by users, so it is
#   vital that you make sure you cannot do anything nasty from these scripts. Either properly restrict
#   them (limited shell), and/or put them in a Docker container.
#
# Format:    Existing directory
# Default:   /etc/replbot/script.d
# Required:  No
#
# script-dir: /etc/replbot/script.d

# Default control/terminal mode. This mode defines how new sessions are started and controlled by the user.
#
# - channel: Both terminal window and user control appear in the main channel
# - thread:  Both terminal window and user control appear in a thread
# - split:   The terminal window is displayed in the main channel, the user input from a thread
#
# Format:    channel|thread|split
# Default:   split
# Required:  No
#
# default-mode: split

# Default window mode. This defines whether white space and new lines are trimmed in the chat terminal window.
#
# - full: The terminal window is left unchanged
# - trim: White spaces are new lines are trimmed from the end
#
# Format:    full|trim
# Default:   full
# Required:  No
#
# default-window-mode: full

# Timeout after which REPL sessions are terminated if there is no user input.
#
# Format:    <number>(hms), must be >1m
# Default:   10m
# Required:  No
#
# idle-timeout: 10m

# Cursor setting for the terminal. Can be "on" to always render the cursor, "off" to turn it off entirely,
# or a duration such as "1s" or "2s" to define the blink rate.
#
# Slack:
#   Please do note that Slack heavily rate limits messages (one message per second per channel), so
#   re-rendering the terminal for the cursor can have side effects.
# Discord:
#   Discord allows 50 requests per second, so a blinking cursor is totally possible in Discord.
#
# Format:    on, off or <number>s
# Default:   on
# Required:  No
#
# cursor: on
