name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          sudo apt-get install tmux vim asciinema
          wget https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64
          chmod +x ttyd.x86_64
          sudo mv ttyd.x86_64 /usr/local/bin/ttyd
      - name: Run tests, formatting, vetting and linting
        run: make check
      - name: Run and upload coverage to codecov.io
        run: make coverage coverage-upload
