name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          sudo apt-get install tmux vim asciinema
          wget https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
          sudo tar -C /usr/local/bin -zxvf gotty_linux_amd64.tar.gz
      - name: Run tests, formatting, vetting and linting
        run: make check
      - name: Run and upload coverage to codecov.io
        run: make coverage coverage-upload
